export const FETCH_FILMS_REQUEST = "FETCH_FILMS_REQUEST"
export const FETCH_FILMS_SUCCES = "FETCH_FILMS_SUCCES"
export const FETCH_FILMS_FAILURE = "FETCH_FILMS_FAILURE"

export const FETCH_PEOPLE_REQUEST = "FETCH_PEOPLE_REQUEST"
export const FETCH_PEOPLE_SUCCES = "FETCH_PEOPLE_SUCCES"
export const FETCH_PEOPLE_FAILURE = "FETCH_PEOPLE_FAILURE"
 